### PR TITLE
create Constant file

### PR DESCRIPTION
**Pull request by 1170300801**
Great work printing Hello World!
Little suggestion, it would be better if you remove all the magic numbers out of your helloworld.java file and create a Constant.java file and define all the static final numbers there. I already did that for you. Hope you will merge.
Peace

### CODE REVIEW

**Comment by 1170300803** [comment]
Thank you for your changes. It is better to store all magic numbers in a Constant file.

**Comment by 1170300803** [comment]
Can you specify the meaning of all magic numbers in the Constant file? Appreciate it.

**Comment by 1170300801** [comment]
package helloworld;

public class Constant {
  public static final int DEFAULT_WIDTH = 300;	// width of the window
  public static final int DEFAULT_HEIGHT = 200;	// height of the window
  public static final int FONT_SIZE = 36;		// the size of the font
}

like this?

**Comment by 1170300803** [comment]
Yes, thank you!

**Pull request merged**
